### ISSUE TITLE
FTPS as fallback to SFTP possible?

### ISSUE THREAD

**Issue by TobiasWantzen** [ojsde/dnb#10]
I’m taking care of two OJS installations on two different servers hosted by two different hosting providers. Since hosting provider A was willing to recompile CURL with SFTP support, hosting provider B is not willing to do so, and says, I should use FTPS instead – both hosting providers support FTPS for CURL out of the box.

Is there a chance to use FTPS instead or as fallback within the plugin as it seems to have a wider support?

Thanks,
Tobias!

**Comment by ronste** [comment]
Hi Tobias,

even if we would implement FTPS support it wouldn't help you with your problem. The DNB only provides SFTP access to the hotfolder server and no FTPS (which uses a ftp connection with an SSL layer). So its not at all our decision.

Best wishes,
Ronald
