### ISSUE TITLE
Plugin for version 3.3?

### ISSUE THREAD

**Issue by felixhelix** [ojsde/dnb#12]
Dear developers,

we think about upgrading to the latest OJS version 3.3.0.7. 
However, we would like to have the DNB export plugin working (thanks for your work, b.t.w :-)
But as I see it, it works only for version 3.2.1 :-( 
Do you plan to update the plugin any time soon?

your's
Felix

**Comment by ronste** [comment]
I am currently working on the upgrade. But it might still need some time. Release will be announced in the PKP Community Forum.

**Comment by felixhelix** [comment]
Hi @ronste,
can I be of any help in developing the plugin? I have some experience in programming, and also could help with testing.
Your's
Felix

**Comment by ronste** [comment]
Hi @felixhelix ,

the development of the new plugin version 1.5 is close to being finished. I currently update Unitests to verify the newly implemented features (e.g. export of Orcid IDs, supplementary material and remote galleys).

Before the official release we will also run test depositions in collaboration with the DNB.

If you want to contribute to these steps please [contact me directly at Freie Universität](https://www.cedis.fu-berlin.de/cedis/mitarbeiter/beschaeftigte/rsteffen.html).

Best wishes,
Ronald
