### ISSUE TITLE
Problem with Upload to DNB Hotfolder

### ISSUE THREAD

**Issue by pentaquarks** [ojsde/dnb#16]
Articles cannot be uploaded although the plugin does not show any error messages. Also, there are no entries in both the php and curl error logs.

Our solution: We created a `.ssh` directory for the apache user (`www-data`), i.e `/var/www/.ssh` and added the `known_hosts` by hand.

Our question: The curl library contains a parameter `CURLOPT_SSH_KNOWNHOSTS` which expects a path to a `known_hosts` file. In the PHP curl extension, this parameter is missing, however, one can pass a MD5 hash to `CURLOPT_SSH_HOST_PUBLIC_KEY_MD5` (which could be read from a different file). So, we are wondering if the verification is really necessary or could be turned off.

What we are using:

- Ubuntu 20.04.5 LTS
- PHP 7.4.3
- curl 7.68.0
- OJS 3.2.1

**Comment by ronste** [comment]
Options implemented in [https://github.com/ojsde/dnb/commit/1eaaa69cae625eae1f1e26484e046bca9ca28cf3](https://github.com/ojsde/dnb/commit/1eaaa69cae625eae1f1e26484e046bca9ca28cf3) as discussed. Ready for testing.
