### ISSUE TITLE
No full article list

### ISSUE THREAD

**Issue by Jannik-Lappe** [ojsde/dnb#17]
Dear ojsde-Team,

when opening the deposit tab inside the plugin i only see 15 out of the nearly 600 articles with no way to go to the next page or filter for others than those 15.
Neither WebConsole nor the apache log show errors.
Is there a solution for this?

Thank you for your help,
Jannik Lappe

PS: Are there plans to publish an update for ojs 3.4?

**Comment by ronste** [comment]
Hi @Jannik-Lappe ,

I assume you are talking about OJS 3.3 and have installed the correct version of the plugin.

That said, the plugin only shows articles that are 1) published and 2) have galleys that can be exported (i.e. pdf or epub galleys). HTML galleys e.g. can not be deposited with the DNB and are not shown.

In case there are pdf or epub galleys missing in the list I would need more information to dig deepter into the issue.

Best wishes,
Ronald

P.S.: There will be a version for OJS 3.4 probably even this year. However, new versions of the plugin undergo extensive testing with the DNB. But to be able to run those tests there first need to be some journals actually running OJS 3.4.

**Comment by Jannik-Lappe** [comment]
Hi Ronald,

Thank you for your reply.
I'll check if some are still missing but I think that this explains it.
Thank you very much

Best regards,
Jannik
