### ISSUE TITLE
Compatibility with OPS

### ISSUE THREAD

**Issue by felixhelix** [ojsde/dnb#19]
Hi all,
we're about to setup a preprint journal at the UCL Cologne. As far as we see it, preprints also have to be delivered to the DNB. Is there a chance to use this plugin for OPS also?
Yours,
Felix

**Comment by ronste** [comment]
> Hi all, we're about to setup a preprint journal at the UCL Cologne. As far as we see it, preprints also have to be delivered to the DNB. Is there a chance to use this plugin for OPS also? Yours, Felix

Hi @felixhelix ,

unfortunately I cannot answer this question. The plugin is being developed for OJS and I never tested it with OPS. Actually I never installed OPS or even looked at it. So I don't know the differences to OJS.

If you have a test instance of OPS I would suggest you try and install it. I too would be interested whether or not it works. In case there are only minor issues I might extend the plugin to support OPS. But this support would certainly only start with OPS 3.4.

Best wishes,
Ronald

**Comment by felixhelix** [comment]
Hi @ronste,
I installed the plugin in OPS 3.3 without problems, but ran into problems exporting submissions: The plugin requires issues. Alas, OPS has none  such :(
Any ideas how to cope with this?
Best wishes,
Felix

**Comment by ronste** [comment]
Hi @felixhelix ,

thanks for testing the plugin with OPS! Interesting to learn that OPS doesn't have issues in general. However, this fact renders the original question much more complex.

From the technical point of view it would be easy to handle this. It would just be about removing all issue information from the export filter. But this is not just a technical question. The metadata scheme used for export to the DNB is in every detail carefully coordinated with the DNB. It is not my decission to add or remove anything.

That said, before going ahead with modifications one would need to contact the DNB about how the lack of issues in OPS should be handled. Do you at all know anyone submitting preprint articles (OPS or not) to the DNB? Do they already have a scheme for that?

Best wishes,
Ronald

**Comment by ronste** [comment]
Hi @felixhelix ,

I close the issue here because different communication channels will be needed to handle it. If you want to proceed please contact me at FU.
