### ISSUE TITLE
"Close"-Button missing

### ISSUE THREAD

**Issue by nmueller18** [ojsde/dnb#4]
Once the DNB-plugin is opened (vers. 1.3, OJS 3.1.2.4), there seems no obvious way to dismiss it and return to the plugins-page. The only way to leave the DNB-plugin is to select one of the menu-options on the left. Therefore, a "Close"-button, e. g. in the top-right corner, would come handy.

**Comment by ronste** [comment]
The DNB plugin does not have a modal setting page that could be closed. The link on the plugin page redirects to the menu entry "Tools -> Import/Export -> DNB Export Plugin" and the plugins page is closed. As with other plugins this is intended behavior. Also there wouldn't be any page to return to if the plugin was opened via the menu. If you want to use the plugin access via the menu is the preferred option.

**Comment by nmueller18** [comment]
Okay, I see. Thank you for the heads-up! I missed the part in the ReadMe about the menu entry in "Tools".
The problem here certainly is a psychological one: after the first install of the plugin, the user (me, at least) first accesses it via the plugin menu and then assumes that this is the correct way. The redirecting process is not apparent.
The most transparent and IMHO the most consistent way would be to make the plugin not directly accessible via the plugin menu at all but redirect the user only to ""Tools -> Import/Export". Then they would know what is happening. This would have helped me, at least.
I just (!) realized that this behaviour is encountered with other plugins as well, but I find it not intuitive.
