### ISSUE TITLE
error to access sftp connection

### ISSUE THREAD

**Issue by sroesner** [ojsde/dnb#8]
error message:

"failed to connect to Hotfolder.dnb.de port 22122" connection refused

**Comment by TobiasWantzen** [comment]
I get the following error:
`The SFTP upload failed for the package file XYZ.tar of the article NN: Protocol "sftp" not supported or disabled in libcurl`

**Comment by sroesner** [comment]
any news here? Unfortunately, still the sam problem when trying to submit 
<img width="1223" alt="3598693C-A21F-4D40-94AA-7E7B99BDDA34" src="https://user-images.githubusercontent.com/44226749/117318184-7a916180-ae8a-11eb-8892-f2bc6af2f210.png">

**Comment by ronste** [comment]
Issue closed because it is a problem with the local server configuration and we are in personal contact.
