### ISSUE TITLE
Option to deliver article page URL instead of galley URL

### ISSUE THREAD

**Issue by TobiasWantzen** [ojsde/dnb#9]
We’d like see the option to deliver the article page URL instead of the galley (PDF) URL.

**Comment by ronste** [comment]
The metadata scheme is defined by the DNB and only adjust the scheme in close collaboration with the DNB. Please contact the DNB team for a discussion of the issue. If the DNB agrees to adjust the metadata scheme they will contact us and I will be happy to implement your request.
